name: safi
description: "SAFI PROJECT"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  fluttertoast: ^9.0.0
  get_it: ^9.0.5
  bloc: ^9.1.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  easy_localization: ^3.0.8
  gap: ^3.0.1
  flutter_svg: ^2.2.1
  flutter_native_splash: ^2.4.7
  animate_do: ^4.2.0
  dots_indicator: ^4.0.1
  phone_form_field: ^10.0.12
  permission_handler: ^12.0.1
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.0+1
  otp_pin_field: ^1.4.1
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  dartz: ^0.10.1
  equatable: ^2.0.7
  persistent_bottom_nav_bar_v2: ^6.2.0
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  dropdown_button2: ^2.3.9
  carousel_slider: ^5.1.1
  flutter_local_notifications: ^19.5.0
  firebase_messaging: ^16.0.4
  envied: ^1.3.1
  flutter_paypal_payment: ^1.0.8
  flutter_stripe: ^12.1.1
  dio: ^5.9.0
  google_maps_flutter: ^2.14.0
  place_picker_google: ^0.0.20
dev_dependencies:
  flutter_test:
    sdk: flutter
  envied_generator: ^1.3.1
  flutter_lints: ^5.0.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/translations/
    - assets/translations/ar.json
    - assets/translations/en.json
